# Generated by Django 5.1.7 on 2025-03-25 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EquivalenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalence_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_1', to='login.item')),
                ('item_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_2', to='login.item')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_offered', models.PositiveIntegerField()),
                ('quantity_requested', models.PositiveIntegerField()),
                ('item_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_offered', to='login.item')),
                ('item_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requested', to='login.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_a', models.PositiveIntegerField()),
                ('quantity_b', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_a', to='login.item')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_b', to='login.item')),
                ('trade_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tradepost')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_a', to='login.profile')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to='login.profile')),
            ],
        ),
    ]
