# Generated by Django 5.1.7 on 2025-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_item_equivalencetable_trade_tradepost_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradepost',
            old_name='quantity_offered',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='item_requested',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='quantity_requested',
        ),
        migrations.AddField(
            model_name='tradepost',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='open', max_length=20),
        ),
    ]
