# Generated by Django 5.1.7 on 2025-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_quantity_offered_tradepost_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='open', max_length=20),
        ),
    ]
